# Build stage

FROM node:latest

WORKDIR /nav-app/

# copy over needed files
COPY . ./

# install packages and build
RUN npm install --unsafe-perm

# Install angular
RUN npm install -g @angular/cli


CMD ng build
